"""Standard transfer and API error categories (Layer C — spec §5.9)."""

VALIDATION_ERROR = "VALIDATION_ERROR"
POLICY_DENIED = "POLICY_DENIED"
SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
TARGET_UNAVAILABLE = "TARGET_UNAVAILABLE"
AUTH_FAILURE = "AUTH_FAILURE"
TRANSFER_TIMEOUT = "TRANSFER_TIMEOUT"
CHECKSUM_FAILED = "CHECKSUM_FAILED"
WORKFLOW_FAILED = "WORKFLOW_FAILED"
INTERNAL_ERROR = "INTERNAL_ERROR"

ALL_CATEGORIES = frozenset(
    {
        VALIDATION_ERROR,
        POLICY_DENIED,
        SOURCE_UNAVAILABLE,
        TARGET_UNAVAILABLE,
        AUTH_FAILURE,
        TRANSFER_TIMEOUT,
        CHECKSUM_FAILED,
        WORKFLOW_FAILED,
        INTERNAL_ERROR,
    }
)
